file(TO_CMAKE_PATH $ENV{NIRVANA_SDK} NIRVANA_SDK_DIR)
set(NIRVANA_TOOLS ${NIRVANA_SDK_DIR}/bin/x64)

set(CMAKE_CXX_COMPILER ${NIRVANA_TOOLS}/clang++.exe)
set(CMAKE_CXX_COMPILER_WORKS ON)
set(CMAKE_C_COMPILER ${NIRVANA_TOOLS}/clang.exe)
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_ASM_COMPILER ${NIRVANA_TOOLS}/clang.exe)
set(CMAKE_RC_COMPILER ${NIRVANA_TOOLS}/llvm-rc.exe)

set(NIDL2CPP ${NIRVANA_TOOLS}/nidl2cpp.exe)
set(CMAKE_CXX_STANDARD_LIBRARIES "")