/*
* Nirvana test suite.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
#include "Test_A1.idl"
#include "Test_V1.idl"
#include "Union.idl"
#include "ValueBox.idl"

module CORBA {
pseudo interface TypeCode;
};

module Test {

const wchar char_const = L'c';
const string string_const = "string_const";
const wstring wstring_const = L"wstring_const";
const long long_const = 123;
const float float_const = 4.56;
typedef double Dbl;
const Dbl double_const = 7.890;

interface I2 : A1
{
	const wchar char_const = L'c';
	const string string_const = "string_const";
	const wstring wstring_const = L"wstring_const";
	const long long_const = 123;
	const float float_const = 4.56;
	typedef double Dbl;
	const Dbl double_const = 7.890;
	const fixed fixed_const = 1.234D;

	long op2 (in long p1);

	long divide (in long a, in long b);

	A1 abstract_op (in A1 in_obj, out A1 out_obj, inout A1 inout_obj);

	V1 value_op (in V1 in_obj, out V1 out_obj, inout V1 inout_obj);

	StringValue box_op (in StringValue in_obj, out StringValue out_obj, inout StringValue inout_obj);

	BoxArray box_array_op (in BoxArray in_ar, out BoxArray out_ar, inout BoxArray inout_ar);

	U union_op (in U in_u, out U out_u, inout U inout_u);

	CORBA::TypeCode type_code_op (in CORBA::TypeCode in_tc, out CORBA::TypeCode out_tc, inout CORBA::TypeCode inout_tc);

	oneway void oneway_op (in long l);
};

const I2 I2_static;

interface I2_factory
{
	I2 create (in long addendum);
};

const I2_factory I2_factory_dynamic;
const I2_factory I2_factory_sysdomain;
const I2_factory I2_factory_V3;

};
