// Test for nested and recorsive struct

struct RecursiveStruct1
{
	long value;
	sequence <RecursiveStruct1> chain;
};

struct RecursiveStruct2;
typedef sequence <RecursiveStruct2> ChainRS2;

struct RecursiveStruct2
{
	long value;
	ChainRS2 chain;
};
