/*
* Nirvana test suite.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/

// Test for nested and recursive struct

struct RecursiveStruct1
{
	long value;
	sequence <RecursiveStruct1> chain;
};

struct RecursiveStruct2;
typedef sequence <RecursiveStruct2> ChainRS2;

struct RecursiveStruct2
{
	long value;
	ChainRS2 chain;
};

struct RecursiveStruct3;
typedef sequence <RecursiveStruct3> ChainRS3;

struct RecursiveStruct4;
typedef sequence <RecursiveStruct4> ChainRS4;

struct RecursiveStruct5
{
	ChainRS3 chain3;
	ChainRS4 chain4;
};

struct RecursiveStruct3
{
	long value;
};

struct RecursiveStruct4
{
	string value;
};

