#ifndef TEST_V1_IDL_
#define TEST_V1_IDL_

module Test {

valuetype V1
{
	short vop1 ();
	long vop2 (in V1 x);

	private short val1;
	public long val2;
	private string val3;
	public V1 val4;

	factory create (in short v1, in string v3);
};

};

#endif
