#include "Test_I1.idl"
#include "Test_I2.idl"
#include "Test_V1.idl"

module Test {

local interface I3 : I1, I2
{
	long op3 (in long p1);

	long divide (in long a, in long b);

	A1 abstract_op (in A1 in_obj, out A1 out_obj, inout A1 inout_obj);

	V1 value_op (in V1 in_obj, out V1 out_obj, inout V1 inout_obj);
};

interface Empty
{
};

interface EmptyWithBase : I2
{};

};
