// Test for unions
#include "Test_I1.idl"

struct S { long len; };

// Variable length union
union U switch (long) {
	case 1: long x;
	case 2: string z;
	case 3:
	case 4: S w;
	default: Test::I1 obj;
};

// Union with implicit default
// The _default () method will be generated
union Z switch (boolean) {
	case TRUE: short s;
};

// Fixed length union
union UFixed switch (long) {
	case 1: long x;
	case 2: double d;
};

enum Tag
{
	First,
	Second
};

// This region has _default ()
union Tagged switch (Tag) {
	case Second: short s;
};

// This region does not have _default ()
union NoDefault switch (Tag) {
	case First: short s;
	case Second: long l;
};

