// Contains imports for all objects declared in the "Test_I2.h" header.
// This file will be generated by the IDL compiler in the future.
#include <CORBA/CORBA.h>
#include <Nirvana/OLF.h>
#include "Test_I2.h"

NIRVANA_OLF_SECTION extern const Nirvana::ImportInterfaceT <::CORBA::TypeCode>
Test::_tc_I2 = { ::Nirvana::OLF_IMPORT_INTERFACE, Test::I2::repository_id_, CORBA::TypeCode::repository_id_ };
